# Generated by Django 5.2.4 on 2025-07-06 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='网站描述')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='friend_avatars/', verbose_name='网站头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
